[workspace]
resolver = "2"
members = [
    "blinky",
    "rtt",
    "rtt_format",
    "ported",
    "ported_int",
    "led_pwm",
    "heap",
    "i2c_ssd1306",
    "serial_control",
    "serial_loopback",
]
[profile.dev]
opt-level = 1
