[workspace]
resolver = "2"
members = [
    "blinky",
    "rtt",
    "rtt_format",
    "ported",
    "ported_int",
    "led_pwm",
    "heap",
    "buzzer",
    "i2c_ssd1306"
]
[profile.dev]
opt-level = 1
